
PREFIX		?= /usr
LIBDIR		?= $(PREFIX)/lib
INCLUDEDIR	?= $(PREFIX)/include

ZLIB_LIBS			?= -lz

LIBANDROID_BASE_LIBNAME		?= android_base
LIBANDROID_BASE_CPPFLAGS	?= -I$(ROOT)/base/include
LIBANDROID_BASE_LIBS		?= -L$(ROOT)/base -l$(LIBANDROID_BASE_LIBNAME)

LIBANDROID_LOG_LIBNAME		?= android_log
LIBANDROID_LOG_CPPFLAGS		?= -I$(ROOT)/include
LIBANDROID_LOG_LIBS		?= -L$(ROOT)/liblog -l$(LIBANDROID_LOG_LIBNAME)

LIBANDROID_CUTILS_LIBNAME	?= android_cutils
LIBANDROID_CUTILS_LIBS		?= -L$(ROOT)/libcutils -l$(LIBANDROID_CUTILS_LIBNAME)
LIBANDROID_CUTILS_CPPFLAGS	?= -I$(ROOT)/include

LIBANDROID_ZIPARCHIVE_LIBNAME	?= android_ziparchive
LIBANDROID_ZIPARCHIVE_CPPFLAGS	?= -I$(ROOT)/include
LIBANDROID_ZIPARCHIVE_LIBS	?= -L$(ROOT)/ziparchive -l$(LIBANDROID_ZIPARCHIVE_LIBNAME)

CONFIG_TARGET_LINUX		?= y
# CONFIG_TARGET_ANDROID is not set

CONFIG_ARCH_X86			?= y
# CONFIG_ARCH_X86_64 is not set
# CONFIG_ARCH_ARM is not set
# CONFIG_ARCH_ARM64 is not set
# CONFIG_ARCH_MIPS is not set

# CONFIG_CPUSETS is not set
# CONFIG_SCHEDBOOST is not set
